snyk/artifactory-snyk-security-plugin

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/exception/SnykRuntimeException.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/PluginConfigurationTest.java, snyk-sdk/src/main/java/io/snyk/sdk/api/v1/SnykClient.java, snyk-sdk/src/main/java/io/snyk/sdk/model/NotificationSettings.java
- set empty default value for `snyk.api.url`
- add documentation snippets for each property
- call `user/me/notification-settings` endpoint to check if api token is valid, if not -> we don't load plugin by artifactory boostrap. It's better if we fails as soon as possible and not on `beforeDownload` extension point.
=> refactor: plugin properties

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.groovy, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/audit/AuditModule.java
This PR adds a new audit module used by `storage->afterPropertyCreate` extension point. This module logs updates for all `forceDownload` (vulns and licenses) properties.
=> feat: add audit logging for 'forceDownload' properties

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/PluginConfigurationTest.java
The new property is for scanner module `snyk.scanner.block-on-api-failure` with default value `true`.
=> feat: allow or block artifact downloads when Snyk API is unavailable

core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/PluginConfigurationTest.java, snyk-sdk/src/main/java/io/snyk/sdk/Snyk.java
This PR fix default user-agent for API client with the custom one.
Custom `User-Agent` header is `snyk-artifactory-plugin/<version>`
=> fix: specify user agent for plugin

.editorconfig, core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.version, core/src/main/java/io/snyk/plugins/artifactory/PropertyLoader.java, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, distribution/src/assembly/distribution-docker.xml, distribution/src/assembly/distribution.xml
This PR adds following functionality:
- create custom user-agent header in form `snyk-artifactory-plugin/<released-plugin-version>`
- *released-plugin-version* will be generated from git tag during the release phase, in case of local development the value is `LOCAL-SHAPSHOT`.
=> chore: load plugin version from property file

core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java
This PR fixes extension recognition for python files (`whl`, `tar.gz`, `zip`, `egg`).
In case of remote PyPI proxy repository the pattern layout must be updated.
=> fix: recognize python extension

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties
This PR documents using 'none' as vulnerability and license issue thresholds.
It was possible earlier but not present in property file.
=> docs: list 'none' value for vulnerability and license issue thresholds

.github/workflows/smoke_tests.yaml
GitHub Action smoke tests for sanity checking different Artifactory versions
Lifted the plugin build part from the Release workflow
Currently failing with older versions, because they are not supported yet.
=> Smoke tests

core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/NpmScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/MavenScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/NpmScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PythonScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
Currently we assume when provided file info that all parameters are available. This leads to us sending `null` to the registry. For example:
```
/api/v1/test/npm/null/null
```
This PR fixes this by failing when any of these values are null and providing that detail in the logs.
=> fix: fail on missing file info

snyk-sdk/src/main/java/io/snyk/sdk/api/v1/SnykClient.java, snyk-sdk/src/main/java/io/snyk/sdk/api/v1/SnykHttpRequestBuilder.java
I noticed packages like `@snyk/protect` weren't being scanned and failed with a 422 error from Registry. This is caused by the lack of URL encoding when creating paths.
e.g.
```
/test/npm/@snyk/protect/1.700.0
```
should be
```
/test/npm/%40snyk%2Fprotect/1.700.0
```
so that it matches the correct route on registry.
=> fix: encode path and query params

core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/exception/SnykAPIFailureException.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/NpmScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/MavenScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/NpmScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PythonScannerTest.java
Note: This merges into #38 
The use or optionals in the package scanners is a bit confusing as there are multiple failure scenarios being aggregated into a single Optional. Optionals for this part of the code isn't ideal as we lose information. Ideally we'd have a `Result<Value, Error>` sort of approach, but that'll require a lot more work and refactoring.
I think it's best if we throw at the scanner level and let the plugin handle it (using configuration). This will bring us closer to a state where the Scanners don't worry about handle various user-visible failures, that'll be the `SnykPlugin`'s job.
=> refactor: handle api failures explicitly

core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java
Note: This is branched off #38 
Artifact properties currently aren't updated. That means if an artifact has 1 vuln previously and now there are 2 new vulns, we'll block on them, but the properties won't be updated to reflect the new vulns. It'll still show 1. This PR fixed that so we always update vuln details.
The other artifact properties seem to be user-defined so those are still only set once to avoid overwriting them. This may have been the original intention. The "force download" feature in general seems to be incomplete as we don't use it in the ScannerModule to avoid blocking downloads.
=> fix: keep artifact issues updated

core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java
PyPi file layouts may often be invalid but since we fallback to regex parsing, this is usually not a problem.
=> chore: remove misleading warning logging

core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java
We're logging too much, especially since we won't be able to scan most artifacts. I've also removed stacktraces for API failures are they're huge and mostly useless since it's all internal.
=> feat: reduce logging and use debug levels

core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java
`validateLicenseIssues` should use `getPropertyOrDefault` just like `validateVulnerabilityIssues` does. Otherwise if the user doesn't set a value, it will be `null` and so never match (similar to `none`) rather the supposed default `low`.
=> fix: fallback to default license threshold

README.md, core/pom.xml, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java, snyk-sdk/src/main/java/io/snyk/sdk/api/v1/SnykClient.java
Currently the `/test` endpoint of the Snyk V1 API builds full dependency graphs for each package it receives. For this plugin, this means that when you do a `pip install mlflow`, you'll wait for the entire transitive dependency line of `mlflow` to be finished before `pip` continues.
The next thing `pip` does is to download the first transitive package of `mlflow`, which gets the same treatment inside Snyk, and thus it continues, wasting large amounts of time.
We recently introduced a fix to Snyk that loosens this logic of the `/test` endpoint and allows for testing of single packages while we wait for a the longer term solution to be completed by Packages and Dependencies and the Package KB project.
There already are pretty thorough integration tests validating the `/test` endpoint …
=> [SUP-926] Performance optimization of scanning endpoints

pom.xml
Fixes: compress-compress ([CVE-2024-25710](https://www.cve.org/CVERecord?id=CVE-2024-25710)) and nimbus-jose-jwt ([CVE-2023-52428](https://www.cve.org/CVERecord?id=CVE-2023-52428)).
=> fix: [OSM-1018] update vulnerable transitive versions

core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java, snyk-sdk/src/main/java/io/snyk/sdk/api/v1/SnykClient.java
Deprecating the topLevelOnly query param because it will be looked to be obsolete in the underlying service. It will become the default behaviour for all PMs.
=> fix: remove topLevelOnly query for reqs

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/PluginConfigurationTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PythonScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java, core/src/test/resources/io/snyk/plugins/artifactory/PropertyLoaderTest/valid-property-file/snykSecurityPlugin.properties, helm-install/install-helm.sh, snyk-sdk-tests/src/test/java/io/snyk/sdk/SnykClientTest.java, snyk-sdk/src/main/java/io/snyk/sdk/SnykConfig.java, snyk-sdk/src/test/java/io/snyk/sdk/api/v1/SnykHttpRequestBuilderTest.java
`snyk.io/api` is the legacy and deprecated way to access Snyk APIs. Let's default to `api.snyk.io` instead.
=> refactor: use api.snyk.io as default url

core/src/main/java/io/snyk/plugins/artifactory/scanner/Ecosystem.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/EcosystemTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
Adding new ecosystem support in small steps because the diff for [the original work](https://github.com/gwnlng/artifactory-snyk-security-plugin/tree/feat/cocoapods-nuget2) is too massive. First baby step = introducing the Ecosystem enum and extracting the file matching logic to it.
=> chore: extract ecosystem enum [OSM-2231]

README.md, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageValidator.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
In preparation for feeding cached test result into the validation step, extracting the validator to its own class.
This commit does not introduce any behavioural changes, only lays the ground for the next iteration. In a follow-up step, we will allow skipping of the test so that gatekeeping is based on cached results.
=> chore: extract Package Validator [OSM-2240]

core/src/main/java/io/snyk/plugins/artifactory/model/Ignores.java, core/src/main/java/io/snyk/plugins/artifactory/model/IssueSummary.java, core/src/main/java/io/snyk/plugins/artifactory/model/MonitoredArtifact.java, core/src/main/java/io/snyk/plugins/artifactory/model/ValidationSettings.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageValidator.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/model/IssueSummaryTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java
In order to let the validation run against cached artefact metadata rather than a full test result, introducing a model representing issue summary.
For the time being, the model is always created from a test result but in a follow-up PR we'll also support deriving it from cached data. This way we'll be able to avoid making an unnecessary Snyk Test request when there is fresh vuln information already.
=> chore: introduce artefact model [OSM-2240]

core/src/main/java/io/snyk/plugins/artifactory/model/IssueSummary.java, core/src/main/java/io/snyk/plugins/artifactory/model/MonitoredArtifact.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/model/IssueSummaryTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
...instead of raw test result.
This refactor sets the scene for reading cached artifacts from properties, which will allow to skip tests when issue data is fresh.
=> chore: write properties based on artefact [OSM-2240]

core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/audit/AuditModule.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/ArtifactProperties.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/ArtifactProperty.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/RepositoryArtifactProperties.java, core/src/main/java/io/snyk/plugins/artifactory/model/Ignores.java, core/src/main/java/io/snyk/plugins/artifactory/model/MonitoredArtifact.java, core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/NpmScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageValidator.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/TestResultConverter.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/properties/FakeArtifactProperties.java, core/src/test/java/io/snyk/plugins/artifactory/model/MonitoredArtifactTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/MavenScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/NpmScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PythonScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
Adding structure to `MonitoredArtifact` and pushing the `TestResult` model into the scanners. Also moving property writing logic into model classes.
This is the final refactor before implementing retrieval of test results from properties to reduce number of requests to Snyk API.
=> chore: extract TestResult from MonitoredArtifact [OSM-2240]

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/ArtifactProperties.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/ArtifactProperty.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/properties/RepositoryArtifactProperties.java, core/src/main/java/io/snyk/plugins/artifactory/model/Ignores.java, core/src/main/java/io/snyk/plugins/artifactory/model/IssueSummary.java, core/src/main/java/io/snyk/plugins/artifactory/model/MonitoredArtifact.java, core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ArtifactCache.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/NpmScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/configuration/properties/FakeArtifactProperties.java, core/src/test/java/io/snyk/plugins/artifactory/model/IssueSummaryTest.java, core/src/test/java/io/snyk/plugins/artifactory/model/MonitoredArtifactTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ArtifactCacheTest.java
Introducing a new configuration property `snyk.scanner.frequency.hours` defaulting to 168 (1 week). As long as there is a test result younger than the TTL indicated by the test frequency, the plugin skips making a test and filters access based on the previous result.
=> feat: skip Snyk tests when cache is fresh [OSM-2240]

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/model/MonitoredArtifact.java, core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ArtifactCache.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/model/MonitoredArtifactTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ArtifactCacheTest.java
Introduces a new param `snyk.scanner.extendTestDeadline.hours`. In case there is a Snyk request error when the next test is due, this parameter allows the plugin to use the previous test result when deciding whether to block access.
=> feat: add extendTestDeadline param to help handle Snyk errors

core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/MavenScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/NpmScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PythonScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/SnykDetailsUrl.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/MavenScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/NpmScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PythonScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/SnykDetailsUrlTest.java
This commit points the details URLs to the new pages (security.snyk.io) and introduces a log message to confirm that the URLs are being written to Artifactory properties.
=> fix: refresh snyk details URLs

core/pom.xml, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageValidator.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java
Adding Snyk package URL to the error messages.
Also adding AssertJ as the vanilla JUnit assertion API is rather limited.
=> feat: include snyk details URL in error messages

pom.xml, snyk-sdk/pom.xml
...to pull in a fix for this vuln: https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538
Also removing the explicit dependency for `jackson-annotations` as it is not needed.
=> chore: upgrade Jackson

core/src/main/java/io/snyk/plugins/artifactory/model/ValidationSettings.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/PackageValidator.java, core/src/test/java/io/snyk/plugins/artifactory/model/ValidationSettingsTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/PackageValidatorTest.java
When severity threshold is set to `none`, download should be allowed regardless of the issues discovered.
=> fix: respect NONE severity threshold

README.md, core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.groovy, core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.properties, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java, core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ArtifactCache.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ArtifactResolver.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ReadOnlyArtifactResolver.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerModule.java, core/src/test/java/io/snyk/plugins/artifactory/model/MonitoredArtifactTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ArtifactCacheTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/ScannerModuleTest.java
This PR aligns the plugin closer with the original behaviour implemented for older versions of Artifactory.
The main contribution of this PR is introduction of a new lifecycle hook `afterRemoteDownload`. This hook is invoked by Artifactory whenever a package is fetched from external repositories. The plugin performs a Snyk Test at this stage. Access to the package is later controlled according to vulnerabilities discovered during the test, and in line with severity thresholds set in the plugin config.
This PR also brings in a new configuration parameter `snyk.scanner.test.continuously` which allows the plugin to periodically re-test packages. The parameter has two values:
- `false` (default). Never re-test packages, respect the result of the test performed when the package was originally …
=> feat: add continuous testing mode

core/src/main/java/io/snyk/plugins/artifactory/configuration/PluginConfiguration.java, core/src/main/java/io/snyk/plugins/artifactory/ecosystem/Ecosystem.java, core/src/main/java/io/snyk/plugins/artifactory/model/TestResult.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/ScannerResolver.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsPackage.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/nuget/NugetPackage.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/nuget/NugetScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/purl/PurlScanner.java, core/src/main/java/io/snyk/plugins/artifactory/scanner/rubygems/RubyGemsPackage.java, core/src/test/java/io/snyk/plugins/artifactory/ecosystem/EcosystemTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsPackageTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/nuget/NugetPackageTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/nuget/NugetScannerTest.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/rubygems/RubyGemsScannerTest.java
Similar to the Gems scanner, CocoaPods and Nuget are powered by Snyk's PURL test API. Disabled by default so these new ecosystems won't be scanned unless explicitly opted-in.
=> feat: add support for CocoaPods and Nuget ecosystems

core/src/main/groovy/io/snyk/plugins/artifactory/snykSecurityPlugin.groovy, core/src/main/java/io/snyk/plugins/artifactory/SnykPlugin.java
Switching the hook which gates artifact downloads from `afterRemoteDownload` to `afterCreate`.
For some ecosystems, e.g. Python and Cocoapods, properties would fail to write during the `afterRemoteDownload`. This would manifest with the following error message in Artifactory logs:
```
Cannot add properties for <repository path> Item not found.
```
The `afterCreate` hook is also attached to initial downloads of artifacts, and properties are successfully created in this context across all ecosystems supported by this plugin.
=> feat: switch first lifecycle hook to afterCreate

README.md
Just in case anyone (myself in 2 days) isn't sure how to quickly set up local ecosystem tools to try out the plugin - adding some tips to the README.
=> docs: document how to set up local dev tools with Artifactory

core/src/main/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsPackage.java, core/src/test/java/io/snyk/plugins/artifactory/scanner/cocoapods/CocoapodsPackageTest.java
For CocoaPods artifacts coming with a `v` prefix in the artifactory path, e.g. `libwebp-v1.3.0.tar.gz`, the parsed version number should skip the prefix i.e. it should be `1.3.0` and not `v1.3.0`.
=> fix: strip off version prefix when parsing CocoaPods paths
